server:
  port: 4848
  forward-headers-strategy: framework


eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

springdoc:
  swagger-ui:
    path: /

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: fda3a9b34d5dd200ee92
            client-secret: bd0004aa728d9944381ae826a0cf51db588635b5