eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: users-service
          uri: http://users-service:8181
          predicates:
            - Path= /users/**
        - id: movies-service
          uri: http://movies-service:8282
          predicates:
            - Path= /movies/**
        - id: comments-service
          uri: http://comments-service:8383
          predicates:
            - Path= /comments/**
        - id: rating-service
          uri: http://rating-service:8484
          predicates:
            - Path= /rates/**
        - id: series-service
          uri: http://series-service:8585
          predicates:
            - Path= /series/**