spring:
  rabbitmq:
    host: rabbitmq-service
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:postgresql://series-db-server:5432/series-db
    username: postgres
    password: 1234

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/